Create sns topics with or without subscriptions
ministryofjustice/opg-ansible-roles pull request #119
Opened 2017-12-08 16:20 UTC by brettminnie

2017-12-08 16:26 UTC, carinadigital commented on roles/ec2-app/tasks/sns.yml
> +  when: not sns_subscriptions|default(False)
why not `sns_topics` condition?

2017-12-08 16:27 UTC, brettminnie commented on roles/ec2-app/tasks/sns.yml
> +  when: not sns_subscriptions|default(False)
main.yml line 105
```
  - name: Create sns resources
      include: sns.yml
      when: sns_topics is defined
      tags:
        - sns
        - iam
```

2017-12-08 16:33 UTC, carinadigital commented on roles/ec2-app/tasks/sns.yml
> +    - name: Create sns topics
Better name please. something like `Create sns topics without default subscriptions`

2017-12-08 16:34 UTC, brettminnie commented on roles/ec2-app/tasks/sns.yml
> +    - name: Create sns topics
:+1:

2017-12-08 16:34 UTC, carinadigital requested changes
A bit or a worry that we have two sources of metadata for sns topics.

2017-12-08 16:39 UTC, carinadigital commented on roles/ec2-app/tasks/sns.yml
> +  when: sns_subscriptions|default(False)
can this variable be better named to show what they are? e.g. `sns_topics_with_subscriptions`

2017-12-11 13:24 UTC, carinadigital approved these changes

2017-12-11 13:24 UTC, merged