Docker file parser role added
ministryofjustice/opg-ansible-roles pull request #21
Opened 2016-12-23 16:47 UTC by brettminnie

2016-12-28 14:31 UTC, tim-mcarthur-moj requested changes

2016-12-28 14:31 UTC, tim-mcarthur-moj commented on roles/parse-docker-files/README.md
> +in the `FROM` portion of the Dockerfile
Please add example usage

2016-12-28 14:31 UTC, tim-mcarthur-moj commented on roles/parse-docker-files/tasks/main.yml
> +  raw: ls ../
might it not be cleaner to use the {{ playbook_dir }} variable as a basis, rather than ls

2016-12-28 14:45 UTC, brettminnie commented on roles/parse-docker-files/tasks/main.yml
> +  raw: ls ../
Good point, will amend

2016-12-28 14:50 UTC, brettminnie commented on roles/parse-docker-files/tasks/main.yml
> +  raw: ls ../
We're looking the directory below `playbook_dir` so that won't work as expected

2016-12-28 14:55 UTC, tim-mcarthur-moj commented on roles/parse-docker-files/tasks/main.yml
> +  raw: ls ../
you can just trim the last field off

2016-12-28 15:06 UTC, brettminnie commented on roles/parse-docker-files/tasks/main.yml
> +  raw: ls ../
that would still give me the contents of `project/ansible` instead of `project` which is what I want, would it not?

2016-12-28 16:30 UTC, tim-mcarthur-moj requested changes

2016-12-28 16:30 UTC, tim-mcarthur-moj commented on roles/parse-docker-files/tasks/commit_files.yml
> +  when: files_changed.stdout | replace('\n', '') != '0'
since git can be so finicky, it may be better to put this into a block with a rescue: block option to catch git failures

2016-12-28 17:01 UTC, brettminnie commented
Cool, makes sense

On 28 Dec 2016 4:30 p.m., "tim-mcarthur-moj" <notifications@github.com>
wrote:

> *@tim-mcarthur-moj* requested changes on this pull request.
> ------------------------------
>
> In roles/parse-docker-files/tasks/commit_files.yml
> <https://github.com/ministryofjustice/opg-ansible-roles/pull/21#pullrequestreview-14574279>
> :
>
> > @@ -0,0 +1,10 @@
> +---
> +
> +- name: Check for modified docker_files
> +  raw: git status | grep Dockerfile | wc -l
> +  register: files_changed
> +
> +- name: Stage, commit and push files
> +  raw: "git add ../*Dockerfile && git commit -m 'Dockerfiles generated by ansible-playbook' && git push"
> +  when: files_changed.stdout | replace('\n', '') != '0'
>
> since git can be so finicky, it may be better to put this into a block
> with a rescue: block option to catch git failures
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ministryofjustice/opg-ansible-roles/pull/21#pullrequestreview-14574279>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF1y2Ncz4bTQUoVmrDhetBEO1v4kkzR4ks5rMo6mgaJpZM4LU8ZL>
> .
>

2016-12-29 17:06 UTC, tim-mcarthur-moj approved these changes

2016-12-29 17:06 UTC, merged