[WIP] Initial pass for creating target specific appdata lists
ministryofjustice/opg-ansible-roles pull request #38
Opened 2017-02-13 17:07 UTC by brettminnie

Need to test in deploy still, want to be able to have some infra appear in the app list for specific targets only

2017-02-17 10:22 UTC, brettminnie commented
test

2017-02-17 11:14 UTC, tim-mcarthur-moj requested changes

2017-02-17 11:14 UTC, tim-mcarthur-moj commented on filter_plugins/opg_custom.py
> +    result = src
please catch errors with `raise errors.AnsibleFilterError('...')`

2017-02-17 11:14 UTC, tim-mcarthur-moj commented on roles/app-data/app-data.md
> +This will then create a structure as seen in the first construct under app_data to be consumed by the playbooks
Do we need to handle the case of an overlap in name keys between the various lists?

2017-02-17 11:38 UTC, brettminnie commented on filter_plugins/opg_custom.py
> +    result = src
:+1:

2017-02-17 11:39 UTC, brettminnie commented on roles/app-data/app-data.md
> +This will then create a structure as seen in the first construct under app_data to be consumed by the playbooks
What would be the order of preference then in the overlap of keys? Currently it will merge them into app_data and overwrite

2017-02-17 12:08 UTC, brettminnie commented
test

2017-02-17 12:11 UTC, tim-mcarthur-moj commented on roles/app-data/app-data.md
> +This will then create a structure as seen in the first construct under app_data to be consumed by the playbooks
probably throw an error about overlapping keys to avoid this

2017-02-17 13:04 UTC, tim-mcarthur-moj commented on roles/app-data/app-data.md
> +This will then create a structure as seen in the first construct under app_data to be consumed by the playbooks
although having the custom data with a higher precedence would allow overriding the app definition per stack, which may be useful

2017-02-17 13:28 UTC, brettminnie commented
I was thinking that, hence the order



On Fri, Feb 17, 2017 at 1:04 PM, tim-mcarthur-moj <notifications@github.com>
wrote:

> *@tim-mcarthur-moj* commented on this pull request.
> ------------------------------
>
> In roles/app-data/app-data.md
> <https://github.com/ministryofjustice/opg-ansible-roles/pull/38#discussion_r101751799>
> :
>
> > +        unhealthy_threshold: "{{ opg_data.elb_health_check.unhealthy_threshold | default(2) }}"
> +        healthy_threshold: "{{ opg_data.elb_health_check.healthy_threshold | default(2) }}"
> +      sg:
> +        - "test-elb-{{ opg_data.stack }}"
> +        - "shared-security-group-{{ vpc_name }}"
> +      elb_sg:
> +        name: 'test-elb-{{ opg_data.stack }}'
> +        desc: 'test elb access'
> +        include_nat_gw: true
> +        ruleset:
> +          - proto: 'tcp'
> +            ports: '80,443'
> +            src: "{{ opg_data.frontend_src | default (opg_data.front_vpn_src) }}"
> +```
> +
> +This will then create a structure as seen in the first construct under app_data to be consumed by the playbooks
>
> although having the custom data with a higher precedence would allow
> overriding the app definition per stack, which may be useful
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ministryofjustice/opg-ansible-roles/pull/38#discussion_r101751799>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF1y2I_QQCmHsMSitJp5ZdlOZf9F_Ou8ks5rdZrfgaJpZM4L_d3F>
> .
>

2017-02-17 13:51 UTC, tim-mcarthur-moj commented on roles/app-data/tasks/main.yml
> +        app_data: "{{ app_data_container | merge_custom_app_data(custom_app_instance_data | default([])) }}"
you shouldn't have the default here on `custom_app_instance_data` as the `when` makes sure it is defined.

perhaps
`when: custom_app_instance_data|default([])|count > 0` would be a better check

2017-02-17 14:09 UTC, brettminnie commented
:+1:

On Fri, Feb 17, 2017 at 1:51 PM, tim-mcarthur-moj <notifications@github.com>
wrote:

> *@tim-mcarthur-moj* commented on this pull request.
> ------------------------------
>
> In roles/app-data/tasks/main.yml
> <https://github.com/ministryofjustice/opg-ansible-roles/pull/38#discussion_r101759712>
> :
>
> >        set_fact:
> -        app_data: "{{ app_data|default([])|merge_custom_app_data(custom_app_instance_data|default([])) }}"
> +        app_data: "{{ app_data_container | merge_custom_app_data(custom_app_instance_data | default([])) }}"
>
> you shouldn't have the default here on custom_app_instance_data as the
> when makes sure it is defined.
>
> perhaps
> when: custom_app_instance_data|default([])|count > 0 would be a better
> check
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ministryofjustice/opg-ansible-roles/pull/38#pullrequestreview-22498704>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF1y2FXG9ODZ97T2Vme3RXGJbi9qcQkrks5rdaXdgaJpZM4L_d3F>
> .
>

2017-02-21 08:28 UTC, tim-mcarthur-moj requested changes

2017-02-21 08:28 UTC, tim-mcarthur-moj commented on filter_plugins/opg_custom.py
> +            raise ValueError('Keys {} are redefined in target list'.format(intersects))
this would be better as AnsibleFIlterError

2017-02-21 09:21 UTC, brettminnie commented on filter_plugins/opg_custom.py
> +            raise ValueError('Keys {} are redefined in target list'.format(intersects))
Caught below and re-raised as ansible filter error in case we get another kind of exception

2017-02-24 14:59 UTC, tim-mcarthur-moj approved these changes

2017-02-24 15:46 UTC, merged