Added maintenance role
ministryofjustice/opg-ansible-roles pull request #53
Opened 2017-04-13 16:42 UTC by brettminnie

Optional role at the vpc level to host a maintenance container

2017-04-18 06:25 UTC, tim-mcarthur-moj requested changes

2017-04-18 06:25 UTC, tim-mcarthur-moj commented on roles/maintenance/files/maintenance.iam.policy
> +{
this file should be in the opg-playbooks repo with the other templates

2017-04-18 06:25 UTC, tim-mcarthur-moj commented on roles/maintenance/meta/main.yml
> +---
this role is already a dependency of the ec2-app role already, so isn't needed here.

2017-04-18 06:28 UTC, brettminnie commented on roles/maintenance/meta/main.yml
> +---
:+1:

2017-04-19 11:01 UTC, tim-mcarthur-moj approved these changes

2017-04-19 11:03 UTC, merged