OPGOPS-1808 NFS templates and other improvements
ministryofjustice/opg-ansible-roles pull request #54
Opened 2017-04-19 16:53 UTC by carinadigital

2017-04-19 16:53 UTC, carinadigital commented
test

2017-04-20 07:44 UTC, brettminnie reviewed
:shipit:

2017-04-20 08:40 UTC, tim-mcarthur-moj requested changes

2017-04-20 08:40 UTC, tim-mcarthur-moj commented on roles/ec2-app/tasks/nfs-templates.yml
> +      with_items: "{{appdata.nfs_templates }}"
missing space.

2017-04-20 09:02 UTC, tim-mcarthur-moj approved these changes

2017-04-20 09:02 UTC, merged