[WIP] Opgops 1910
ministryofjustice/opg-ansible-roles pull request #55
Opened 2017-04-26 10:46 UTC by brettminnie

* Refactored RDS creation into own task
 * RDS SG creation happens earlier in stack creation to avoid timing issues

2017-05-08 17:32 UTC, tim-mcarthur-moj commented on roles/awscommon/tasks/main.yml
> +- name: Add instances to runtime group for later usage
this doesn't provide us with logical groupings by function which allows per group vars

2017-05-09 11:19 UTC, tim-mcarthur-moj requested changes

2017-05-09 11:19 UTC, tim-mcarthur-moj commented on roles/awscommon/tasks/main.yml
> +- name: Add target level instances to runtime group for later usage
this breaks on existing environments where the role tag is missing from jump and master

2017-05-09 11:22 UTC, brettminnie commented on roles/awscommon/tasks/main.yml
> +- name: Add target level instances to runtime group for later usage
@tim-mcarthur-moj addressed, defaulted to `unknown` if missing

2017-05-09 17:52 UTC, tim-mcarthur-moj approved these changes

2017-05-09 17:53 UTC, tim-mcarthur-moj commented
tested on
https://jenkins.service.opg.digital/job/OPG/job/base_ansible_runner/
job numbers: 1435,1436,1437

2017-05-09 17:53 UTC, merged