Opgops 2005
ministryofjustice/opg-ansible-roles pull request #60
Opened 2017-06-01 09:46 UTC by brettminnie

2017-06-01 13:25 UTC, tim-mcarthur-moj requested changes

2017-06-01 13:25 UTC, tim-mcarthur-moj commented on roles/admins/tasks/users.yml
> +        mode: 0600
700 is the correct mode for these dirs, with 600 for files

2017-06-01 13:25 UTC, tim-mcarthur-moj commented on roles/common/tasks/directories.yml
> +    - /var/log
surely we don't need this?

2017-06-01 13:25 UTC, tim-mcarthur-moj commented on roles/cron/tasks/main.yml
> +    cron_paths: "/usr/local/bin:/usr/bin:/bin"
are `sbin` directories not also needed in path

2017-06-01 13:25 UTC, tim-mcarthur-moj commented on roles/docker-service/README.md
> +This module is an extension of the docker compose formula allowing the formula to deliver an ecs service or a docker compose file.
needs updating to reflect how it is used with ansible

2017-06-01 13:37 UTC, brettminnie commented on roles/cron/tasks/main.yml
> +    cron_paths: "/usr/local/bin:/usr/bin:/bin"
Good call

2017-06-01 13:40 UTC, brettminnie commented on roles/docker-service/README.md
> +This module is an extension of the docker compose formula allowing the formula to deliver an ecs service or a docker compose file.
This entire role needs to be updated to play nicely with ansilble, was committed so I don't lose it while I migrate all the other things

2017-06-01 13:48 UTC, brettminnie commented on roles/common/tasks/directories.yml
> +    - /var/log
Are`srv/` and `data/` auto cucumbered?

I agree with `/var/log`

2017-09-04 08:23 UTC, carinadigital requested changes
I think it could be better to split out new roles in separate PRs, that can be reviewed an merged earlier

2017-09-04 08:23 UTC, carinadigital commented on filter_plugins/opg_custom.py
> +    res_dict = {}
Would be nice to have a better name and sentence describing what this does e.g.
``` combine_dicts()```
``` Takes a list of dictionaries and returns a combined dictionary. keys are overwritten is present in more that one dictionary```

2017-09-04 08:23 UTC, carinadigital commented on roles/admins/tasks/main.yml
> +  with_items: "{{ admins | d([]) }}"
What do you think about using longform  `default()` everywhere?

2017-09-04 08:23 UTC, carinadigital commented on roles/bootstrap/files/bash-prompt.sh
> +    PS1="\[\033[01;31m\](${OPG_ENVIRONMENT}-${OPG_STACKNAME})\[\e[m\]\[\033[01;32m\]$PS1\[\033[00m\] "
Can you comment what type of prompt this produces?

2017-09-04 08:23 UTC, carinadigital commented on roles/bootstrap/tasks/hostname.yml
> +    ec2_metadata_url: 'http://169.254.169.254/latest/meta-data'
Isn't this fact already in `common` role above?

2017-09-04 08:23 UTC, carinadigital commented on roles/bootstrap/tasks/packages.yml
> +    - joe
why `joe`?

2017-09-04 08:23 UTC, carinadigital commented on roles/collectd/README.md
> +###collectd
Could we not have leveraged something like https://github.com/azavea/ansible-collectd ?

2017-09-04 08:24 UTC, Azulinho commented on roles/admins/tasks/main.yml
> +  with_items: "{{ admins | d([]) }}"
+1

2017-09-04 08:24 UTC, brettminnie commented on roles/bootstrap/tasks/packages.yml
> +    - joe
was a default from old systems, I did ask if it was required, no-one answered me so I left it in

2017-09-04 08:24 UTC, brettminnie commented on roles/bootstrap/tasks/hostname.yml
> +    ec2_metadata_url: 'http://169.254.169.254/latest/meta-data'
Good spot, I must have missed this

2017-09-04 08:25 UTC, brettminnie commented on roles/collectd/README.md
> +###collectd
Based on our opg-collectd formula, I'll check the differences

2017-09-04 08:26 UTC, Azulinho commented on roles/bootstrap/files/bash-prompt.sh
> +    PS1="\[\033[01;31m\](${OPG_ENVIRONMENT}-${OPG_STACKNAME})\[\e[m\]\[\033[01;32m\]$PS1\[\033[00m\] "
I was about to say this is baked in the AMI, but remembered 1701 is not merged yet. so will keep my mouth shut

2017-09-04 08:50 UTC, brettminnie commented on roles/bootstrap/files/bash-prompt.sh
> +    PS1="\[\033[01;31m\](${OPG_ENVIRONMENT}-${OPG_STACKNAME})\[\e[m\]\[\033[01;32m\]$PS1\[\033[00m\] "
It is and it isn't, the version baked into the ami breaks on display somehow, so I tweaked it, we need to consolidate the two @Azulinho

2017-09-06 09:23 UTC, brettminnie commented on roles/bootstrap/tasks/hostname.yml
> +    ec2_metadata_url: 'http://169.254.169.254/latest/meta-data'
Upon testing this is not picking it up from the previous scope, I've left it redeclared for now

2017-09-06 10:50 UTC, brettminnie commented
Will be closed when sub prs are merged in

2017-09-06 14:36 UTC, brettminnie commented
Closed via #83, #84, #85,#86, #87, #88, #89, #90, #91, #92, #93, #94

2017-09-06 14:36 UTC, closed without merging