make regex for <component>-<stack-name> more restrictive
ministryofjustice/opg-ansible-roles pull request #68
Opened 2017-07-17 15:00 UTC by Azulinho

This fixes:
https://jenkins.service.opg.digital/job/OPG/job/base_ansible_runner/2849/

Green build using this branch:
https://jenkins.service.opg.digital/job/OPG/job/base_ansible_runner/2850/console

2017-07-17 15:10 UTC, tim-mcarthur-moj requested changes

2017-07-17 15:10 UTC, tim-mcarthur-moj commented on filter_plugins/ec2_custom.py
> +VALID_APP_COMPONENT_NAMES = ["frontend",
this should be a variable that can be supplied to the filter from ansible, otherwise we have to maintain this var in the filter

2017-07-17 15:10 UTC, tim-mcarthur-moj commented on filter_plugins/ec2_custom.py
> +            if pattern.match(launch_config['LaunchConfigurationName']):
the launch config name includes a hash suffix to ensure uniqueness, so this would not match with the `$` on L151

2017-07-17 15:38 UTC, carinadigital commented on filter_plugins/ec2_custom.py
> +            pattern = re.compile("^{}-{}$".format(component_regex, stack_name))
A comment/example here would make this more readable.

2017-07-17 15:52 UTC, Azulinho commented on filter_plugins/ec2_custom.py
> +            if pattern.match(launch_config['LaunchConfigurationName']):
nope, it doesn't, its just <component>-<stack name>

2017-07-17 15:52 UTC, Azulinho commented on filter_plugins/ec2_custom.py
> +            if pattern.match(launch_config['LaunchConfigurationName']):
btw, I've already tested this code in jenkins as mentioned in the JIRA

2017-07-17 15:53 UTC, Azulinho commented on filter_plugins/ec2_custom.py
> +            pattern = re.compile("^{}-{}$".format(component_regex, stack_name))
will add one

2017-07-17 15:55 UTC, Azulinho commented on filter_plugins/ec2_custom.py
> +            if pattern.match(launch_config['LaunchConfigurationName']):
oh, it's not consistent across the different apps

2017-07-17 15:58 UTC, Azulinho commented on filter_plugins/ec2_custom.py
> +VALID_APP_COMPONENT_NAMES = ["frontend",
how do you propose injecting those component names to ansible? considering they are named differently across the different apps?
in jenkins?

2017-07-17 16:25 UTC, tim-mcarthur-moj commented on filter_plugins/ec2_custom.py
> +VALID_APP_COMPONENT_NAMES = ["frontend",
at runtime only the options for the specific project are relevant.  The args can be supplied to the filter via group_vars

2017-07-18 08:15 UTC, tim-mcarthur-moj commented on filter_plugins/ec2_custom.py
> +            if pattern.match(launch_config['LaunchConfigurationName']):
{code}
14:55:51 TASK [ec2-app : Extract stack specific lc's] ***********************************
14:55:51 ok: [localhost] => {"ansible_facts": {"env_launch_configs": []}, "changed": false}
14:55:51 
{code}

It hasn't selected any configs to delete

2017-07-18 11:07 UTC, Azulinho commented on filter_plugins/ec2_custom.py
> +            if pattern.match(launch_config['LaunchConfigurationName']):
yeap, as expected. it didn't select anything else than the match 'production', so LaunchConfigurations of 'production01' were skipped

2017-07-18 13:31 UTC, tim-mcarthur-moj approved these changes

2017-07-18 13:31 UTC, merged