WIP: BAU: Simplify S3 bucket creation. Allows choice of policies.
ministryofjustice/opg-ansible-roles pull request #71
Opened 2017-08-01 14:52 UTC by carinadigital

2017-08-02 15:08 UTC, brettminnie commented on roles/ec2-app/tasks/destroy_stack.yml
> +# Commented out intentionally. We want to keep s3 buckets and data between our builds
why not add this in a switch type scenario

```
- block:
     when: destroy_buckets is defined and destroy_buckets
```

2017-08-02 15:12 UTC, brettminnie reviewed
See comment on destroy_stack.yml

2017-08-02 15:16 UTC, brettminnie requested changes
Arrrgh! Stupid github :dagger:

2017-08-03 08:22 UTC, tim-mcarthur-moj requested changes
all yaml files should have --- before the vars are defined.

2017-08-03 12:49 UTC, tim-mcarthur-moj approved these changes

2017-08-03 14:12 UTC, merged